# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /data/devel/redpitaya/vivado/redpitaya/red_pitaya.xdc

# Block Designs: bd/red_pitaya_ps_1/red_pitaya_ps_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1 || ORIG_REF_NAME==red_pitaya_ps_1} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_axis_decimator_0_0/red_pitaya_ps_1_axis_decimator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_axis_decimator_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_axis_decimator_0_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_axis_packetizer_0_0/red_pitaya_ps_1_axis_packetizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_axis_packetizer_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_axis_packetizer_0_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_axis_red_pitaya_adc_0_0/red_pitaya_ps_1_axis_red_pitaya_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_data_fifo_0/red_pitaya_ps_1_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_data_fifo_0 || ORIG_REF_NAME==red_pitaya_ps_1_data_fifo_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_red_pitaya_ps_0/red_pitaya_ps_1_red_pitaya_ps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_red_pitaya_ps_0 || ORIG_REF_NAME==red_pitaya_ps_1_red_pitaya_ps_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_red_pitaya_ps_axi_periph_0/red_pitaya_ps_1_red_pitaya_ps_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_red_pitaya_ps_axi_periph_0 || ORIG_REF_NAME==red_pitaya_ps_1_red_pitaya_ps_axi_periph_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_rst_red_pitaya_ps_125M_0/red_pitaya_ps_1_rst_red_pitaya_ps_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_rst_red_pitaya_ps_125M_0 || ORIG_REF_NAME==red_pitaya_ps_1_rst_red_pitaya_ps_125M_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_util_ds_buf_0_0/red_pitaya_ps_1_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_util_ds_buf_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_xlconstant_0_0/red_pitaya_ps_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_xlconstant_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_axis_clock_converter_0_0/red_pitaya_ps_1_axis_clock_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_axis_clock_converter_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_axis_clock_converter_0_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_util_vector_logic_0_0/red_pitaya_ps_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_util_vector_logic_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_axi_cfg_register_0_0/red_pitaya_ps_1_axi_cfg_register_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_axi_cfg_register_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_axi_cfg_register_0_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_xlconstant_0_1/red_pitaya_ps_1_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_xlconstant_0_1 || ORIG_REF_NAME==red_pitaya_ps_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_axi_cfg_register_0_1/red_pitaya_ps_1_axi_cfg_register_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_axi_cfg_register_0_1 || ORIG_REF_NAME==red_pitaya_ps_1_axi_cfg_register_0_1} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_axi_fifo_mm_s_0_1/red_pitaya_ps_1_axi_fifo_mm_s_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_axi_fifo_mm_s_0_1 || ORIG_REF_NAME==red_pitaya_ps_1_axi_fifo_mm_s_0_1} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_dac_out_0_0/red_pitaya_ps_1_dac_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_dac_out_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_dac_out_0_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_xbar_0/red_pitaya_ps_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_xbar_0 || ORIG_REF_NAME==red_pitaya_ps_1_xbar_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_4/red_pitaya_ps_1_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_auto_pc_4 || ORIG_REF_NAME==red_pitaya_ps_1_auto_pc_4} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_0/red_pitaya_ps_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_auto_pc_0 || ORIG_REF_NAME==red_pitaya_ps_1_auto_pc_0} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_1/red_pitaya_ps_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_auto_pc_1 || ORIG_REF_NAME==red_pitaya_ps_1_auto_pc_1} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_2/red_pitaya_ps_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_auto_pc_2 || ORIG_REF_NAME==red_pitaya_ps_1_auto_pc_2} -quiet] -quiet

# IP: bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_3/red_pitaya_ps_1_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_auto_pc_3 || ORIG_REF_NAME==red_pitaya_ps_1_auto_pc_3} -quiet] -quiet

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_data_fifo_0/red_pitaya_ps_1_data_fifo_0_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_red_pitaya_ps_0/red_pitaya_ps_1_red_pitaya_ps_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_red_pitaya_ps_0 || ORIG_REF_NAME==red_pitaya_ps_1_red_pitaya_ps_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_rst_red_pitaya_ps_125M_0/red_pitaya_ps_1_rst_red_pitaya_ps_125M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_rst_red_pitaya_ps_125M_0 || ORIG_REF_NAME==red_pitaya_ps_1_rst_red_pitaya_ps_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_rst_red_pitaya_ps_125M_0/red_pitaya_ps_1_rst_red_pitaya_ps_125M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_rst_red_pitaya_ps_125M_0 || ORIG_REF_NAME==red_pitaya_ps_1_rst_red_pitaya_ps_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_rst_red_pitaya_ps_125M_0/red_pitaya_ps_1_rst_red_pitaya_ps_125M_0_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_util_ds_buf_0_0/red_pitaya_ps_1_util_ds_buf_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==red_pitaya_ps_1_util_ds_buf_0_0 || ORIG_REF_NAME==red_pitaya_ps_1_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_util_ds_buf_0_0/red_pitaya_ps_1_util_ds_buf_0_0_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_axis_clock_converter_0_0/red_pitaya_ps_1_axis_clock_converter_0_0_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_axi_fifo_mm_s_0_1/red_pitaya_ps_1_axi_fifo_mm_s_0_1_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_4/red_pitaya_ps_1_auto_pc_4_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_0/red_pitaya_ps_1_auto_pc_0_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_1/red_pitaya_ps_1_auto_pc_1_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_2/red_pitaya_ps_1_auto_pc_2_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/ip/red_pitaya_ps_1_auto_pc_3/red_pitaya_ps_1_auto_pc_3_ooc.xdc

# XDC: /data/devel/redpitaya/vivado/adc_dac/adc_dac.gen/sources_1/bd/red_pitaya_ps_1/red_pitaya_ps_1_ooc.xdc
